### ISSUE TITLE
Music playback stops during song change when app is in the background

### ISSUE THREAD

**Issue by csaavedra** [jellyfin/jellyfin-android#1208]
### Describe the bug

When the screen is off while playing music, after some time Jellyfin fails to switch to the next song and playback stops. When I put the screen on again, it shows me the dialog to choose server, as if it had lost connectivity to the server. I don't know what the problem is, but maybe Jellyfin loses network connectivity because Android is optimizing for battery usage?

This shouldn't happen, I suppose other media players (like Spotify) request certain permissions in order to be able to continue working while the screen is off, but Jellyfin seems to miss those. I am familiar with Android development so I don't know what could the reason be.

How to reproduce:

1. Start playing an album.
2. Put the screen off.
3. If the songs are short, Jellyfin will continue playing some of them for a while.
4. After about 10 min., when a song ends, it won't go to the next one and playback will stop.
5. Unlock the phone screen, the server error dialog is visible.

### Application version

2.5.3

### Where did you install the app from?

Google Play

### Device information

Moto edge 20 lite

### Android version

Android 12

### Jellyfin server version

10.8.11

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by csaavedra** [comment]
Additional info: I have configured the app battery mode to "Unrestricted".

**Comment by joshuamkite** [comment]
This issue is also affecting me. I see a trail of reports of this same issue here on GitHub [e.g.](https://github.com/jellyfin/jellyfin-android/issues/948) and elsewhere, e.g. [Reddit](https://www.reddit.com/r/jellyfin/comments/jfkuij/jellyfin_stops_playing_next_song_if_jellyfin_is/) but no solutions. In each case we see the issue was closed by a bot without effective resolution. I am using a Google Pixel 6 and have app battery usage set to 'unrestricted' - see screenshot - but as soon as I switch away from having the app in the foreground music playback stops. This makes it unusable for audio playback. None of my other audio apps have this problem, e.g. Spotify; VLC

![Screenshot (11 Feb 2024 11_27_40)](https://github.com/jellyfin/jellyfin-android/assets/22547752/db97c12d-27aa-41c7-aa46-19e1196d2847)

**Comment by Arthessia** [comment]
Facing also the issue, I correctly configured my app with all battery options to set, and music stops randomly.

It started when I upgraded to android 14

**Comment by ipod86** [comment]
Same here

**Comment by joshuamkite** [comment]
Hey @csaavedra Please could you reopen - this is clearly an unresolved issue

**Comment by csaavedra** [comment]
I'm not reopening this because I later realized that this was a misconfiguration of my VPN client. It was stopping all traffic when the phone was idle. Configuring it properly solved this problem for me. 


Open a new issue if your problem is different and persists.

**Comment by joshuamkite** [comment]
I've opened a new bug [here](https://github.com/jellyfin/jellyfin-android/issues/1378). Please could those reporting after me paste their comments from here to there:
@Arthessia 
@mike4today 
@ipod86

**Comment by pixel24** [comment]
Here, the same problem. Pixel 6 Pro / Android 14.

**Comment by Lost-Ones** [comment]
Hello,   I also am facing this issue Pixel 7 / Andriod 14, app verison 2.6.1.  Songs will not auto play when the app is running in the background.  I have insured the the battery is allowed to have background usage.
