### ISSUE TITLE
Account Manager login

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin-android#163]
**Describe the bug**
When i select the Name field and want to autofill teh Login credentials it dont autofill both fields. it autofill only one field at a time

**To Reproduce**
1. go to the login screen
2. use android autofill password function to autofill the login credentials
3. and now only one of the fields get filled automatic

**Expected behavior**
when i use the autofill function from android (set to bitwarden) the login credentials should be filled in correct

**Logs**
dont know where they are if local logs get created

**Screenshots**

**System (please complete the following information):**
 - App version: 1.0.2
 - Android version: Android 10 oxygen OS
 - Device manufacturer and model: Oneplus Nord
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: [web player or integrated player (ExoPlayer)] ??? dont know
 - Account Manager: Bitwarden version 2.6.1

**Additional context**
correspond to #142

Greetings
Xyz00777

**Comment by Maxr1998** [comment]
Could you try the beta version (by signing up for it in the Play Store or by downloading the latest GitHub release)?

**Comment by Xyz00777** [comment]
i singed up a hour ago but the signup is still in progress :/

**Comment by Xyz00777** [comment]
okay now im signed up and its still the same problem with the autofill function... :(

**Comment by CarlosOlivo** [comment]
`chromium: [WARNING:autofill_agent.cc(797)] Autofill suggestions are disabled because the document isn't a secure context.`

I don't know since when, but it seems that if you want to use the autofill framework you need at least that the connection to be secure (HTTPS). This depends on the webview implementation. One way to fix it would be by adding [custom support](https://developer.android.com/guide/topics/text/autofill-optimize#custom), but it sounds like a lot of work. Or the reverse proxy + SSL certificate combo.

Example with local HTTP Jellyfin server
![image](https://user-images.githubusercontent.com/25919231/96800626-5c22b780-13cb-11eb-81d4-389436ff0596.png)

Example with https://demo.jellyfin.org/stable
![image](https://user-images.githubusercontent.com/25919231/96800663-6fce1e00-13cb-11eb-9eb5-2f3c8b009a6a.png)

**Comment by Xyz00777** [comment]
Im using https on my Media server, but Even than its not working properly :( for me it looks more like the naming of the field is not correct and because of that bitwarden cant fill in them well

**Comment by CarlosOlivo** [comment]
I'm not sure about that, it works fine with Enpass Manager

![20201021_195058](https://user-images.githubusercontent.com/25919231/96805798-0b658b80-13d8-11eb-8993-8b9656072e55.gif)

**Comment by Xyz00777** [comment]
At my system it looks like these. When i chose the password field than it happens sometimes that it Can fill in the Name field to bot not every tim

**Comment by Xyz00777** [comment]
![Uploading 20201022_185704.gif…]()
Here the video

**Comment by MominRaza** [comment]
Android 14, using Google password manager.
It is **not offering** to save password after logging in.
I manually added password for Jellyfin app in Google password manager, but it still **not auto filling the password**.

Chrome on laptop/android is working fine.
