### ISSUE TITLE
App shows "Choose a chromecast" rather than casting.

### ISSUE THREAD

**Issue by Lightning2X** [jellyfin/jellyfin-android#187]
**Intended behaviour:**
App lists chromecast and it is selectable.

**Actual behaviour:**
After updating to the most recent version of the app it seemed to have broken my casting ability. Before, if you chose the cast button the chromecast would be listed under it's name, was immediately selectable and would function as normal. However, after the update the app shows a dialog with "choose chromecast" where there is sadly no chromecast visible. My phone still detects the chrome cast as I can still stream netflix and screen share my device. This doesn't seem to be the same issue as #79 or #184.
![Screenshot_2019-09-07-23-29-29](https://user-images.githubusercontent.com/32514161/64480511-6aaf0f00-d1c9-11e9-863a-49f16af10334.png)

**Comment by lewazo** [comment]
Fixed in https://github.com/jellyfin/cordova-plugin-chromecast/pull/35

Will be fixed in the next update of the android app. In the meantime you can install an older apk or access your jellyfin server through the Chrome browser (mobile or desktop) and from there you'll be able to cast to your Chromecast.

**Comment by Lightning2X** [comment]
Nice! Sounds good man, thanks as always to the team for their hard work <3
