### ISSUE TITLE
Notification play/pause bar won't go away when closing the app.

### ISSUE THREAD

**Issue by shaynethiessen** [jellyfin/jellyfin-android#206]
Notification play/pause bar won't go away when closing the app. I have to "force close" the app to get rid of it. 

I think it might have something to do with poor cell service and the audio file failing to buffer and stopping playback, but I haven't found a way to reproduce this.

I use the app several times a day, and it happens at least once.

 - App version: 2.0.1
 - Android version: Android 10
 - Device manufacturer and model: Samsung Galaxy S20

**Comment by purcell** [comment]
Yes, this happens a lot to me too, in a domestic setting and using the latest versions. Here's roughly how it plays out:

- Play something with jellyfin-web in a web browser on a desktop computer, streaming from a jellyfin server on the same network. (Using firefox on macOS in my case.)
- In jellyfin-android, choose "play on" and select that browser instance, in order to remote-control it.
- Close the web browser tab when done
- Android play notification persists indefinitely (e.g. 24hrs)

Then, I either try to close the jellyfin-android app (which has no effect), or re-enter the app much later. In neither case is the notification removed: when the app is restarted, it is able to see that the web browser instance is gone, but the notification is unaffected. Force-closing the app via the hanging notification is the only solution I've found, as reported above.

What I _suspect_ in my case is that the idle android app is getting suspended, and if the web playback instance goes away during that time, the app state gets confused. But completely unsure, to be fair.

Anyway, it's also worth noting here that I love the app, and appreciate the developers' hard work! ❤️
