### ISSUE TITLE
Exo Player won't let me stop playing an episode.

### ISSUE THREAD

**Issue by ChojinDSL** [jellyfin/jellyfin-android#266]
I'm experimenting with the native video player in the android jellyfin app.
It's a weird issue, but I've been able to reproduce it on multiple systems. 

If I start playing a TV Show, then pause it and then try to go back to the main jellyfin page. The episode just reloads and starts to play from the the beginning again. The only way to get out is to kill the app completely.

The strange thing is, this only happens with TV episodes. 
I can exit out of playing a movie just fine, and also playing TVheadend recordings. I just can't stop an episode.

Am I not using the correct method? E.g. to get back into the main window, I use android's "back" button. Is there a different way to do it?

**Comment by nielsvanvelzen** [comment]
Can you please use our template? Some relevant information is missing now (like the server version).

**Comment by ChojinDSL** [comment]
My bad.



**Describe the bug**
When playing a TV show episode using the native video player in the jellyfin android app, I am unable to stop and exit back to jellyfin. If I stop, and then press the android "back" button, I quickly see the jellyfin window of the TV show, it quickly reloads and then starts playing again. So in essence I get stuck playing the tv show with now way of exiting, unless I force close the app completely. 
This doesn't happen with Movies or TVheadend recordings. Only with TV Shows

**To Reproduce**
go to settings/client settings 
Select "Native Player" as the video app.
Now try to play an episode of a TV show. Stop, then try to exit back to the jellyfin window where you can either select another episode, or go back and select another TV show entirely.

**Expected behavior**
I expect that when I tap the "back" button in android, that I get taken back to the previous jellyfin window.

**Logs**


**Screenshots**


**System (please complete the following information):**
 - App version: 2.2.2
 - Android version: Android version 9
 - Device manufacturer and model: [Samsung galaxy Note 8]
 - Jellyfin server version: [10.6.4] (docker)
 - The type of video player implementation used: [integrated player]


I can reproduce this bug on my Kindle HDX7 Tablet which is running lineageos and Android 9.

**Comment by CarlosOlivo** [comment]
https://github.com/jellyfin/jellyfin-android/pull/111#issuecomment-689718160
https://github.com/jellyfin/jellyfin-android/pull/111#issuecomment-689719511

**Comment by redactedscribe** [comment]
I'm also experiencing this. It's quite the annoying bug, but thankfully if you tiptoe carefully, you can avoid getting stuck in the loop. I have to use the Native player because the HTML one does nothing but display a static frame, and the External player doesn't even launch anything external (despite having VLC installed), and just defaults to using the HTML player again.

To avoid the bug when watching something episodic, do not clicking any of the Play buttons that would queue multiple episodes (I assume this is what's happening). That is to say, after selecting a show, don't press the Play button under the primary image (the button next to the five others in a row), and don't press the Play button on any of the the season images either. The only way to watch anything episodic and still be able to back-out to the series screen, is by either pressing the Play on the Next Up episode mage, or going into a season and selecting precisely the episode you want to watch. This way, you should be able to press back and stop playback every time.

Assuming a season with two episodes, what the bug seems to be doing is autoplaying the next episode once back is pressed, so to escape playback, you must to get to the end of the queued list (or force quit). In this case that would mean, pressing back on video one, loading video two, and pressing back on that too, finally exiting to the series screen. You can imagine that this sucks given that most seasons have more than two episodes. The client app setting to automatically play the next episode has no bearing on this behaviour.

With that lead, maybe a fix could be discovered? It's unfortunate that after six months of not using the app and now trying again (new version), that the app doesn't run too great on my phone. Maybe the out-of-synch subtitles bug has been fix since 🤞

Thanks for your efforts.

---

**System:**

* App version: 2.2.3
* Android version: Android version 9
* Device manufacturer and model: Moto G4
* Jellyfin server version: 10.7.1 (from scoop)
* The type of video player implementation used: Native/Exo

**Comment by redactedscribe** [comment]
> the External player doesn't even launch anything external (despite having VLC installed),

After reading https://github.com/jellyfin/jellyfin-android/issues/332, it made me test whether this is an issue with which Play button I choose to press, and it is. I can get the external player (VLC) to launch if I only press Play on the Next Up / individual episode in a season list (as detailed in my above post).

**Comment by Maxr1998** [comment]
This is fixed in 2.3.0, closing.
