### ISSUE TITLE
How to build app with custom server predefined?

### ISSUE THREAD

**Issue by alexsoussa** [jellyfin/jellyfin-android#281]
Hello, I want to build the app with a custom server predefined. Is this possible?

Thanks!

**Comment by nielsvanvelzen** [comment]
This is not possible without making changes to the code yourself.

**Comment by alexsoussa** [comment]
> This is not possible without making changes to the code yourself.

Can you explain me which file I have to edit? 

I need to do this because if I do an apk with a WebView to the server, I couldn't use chromecast because the server doesn't have SSL.

Thanks a lot!

**Comment by nielsvanvelzen** [comment]
The easiest solution is probably to add some additional JavaScript injections in the gulpfile. You'll need to look into the web code what to change for that though.

Be sure to comply to our [LICENSE](https://github.com/jellyfin/jellyfin-android/blob/master/LICENSE.md) when making changes

**Comment by alexsoussa** [comment]
Okay and if I change the WEB_DIR to the IP of my server it would work?

Because I have the jellyfin web app working there. You can take a look here: http://188.95.148.10:8096

And if I put a SSL Certificate, I would be able to share the videos to Apple TV, Chromecast or similar?

I really appreciate your help!

**Comment by JustAMan** [comment]
> I need to do this because if I do an apk with a WebView to the server, I couldn't use chromecast because the server doesn't have SSL.

This shouldn't be true. Jellyfin Android app should be casting to Chromecast just fine even with your server using http.

Baking server in would give you nothing regarding the Chromecast support anyway.

**Comment by alexsoussa** [comment]
> > I need to do this because if I do an apk with a WebView to the server, I couldn't use chromecast because the server doesn't have SSL.
> 
> This shouldn't be true. Jellyfin Android app should be casting to Chromecast just fine even with your server using http.
> 
> Baking server in would give you nothing regarding the Chromecast support anyway.

Yes I know.  That is why I need to make an application for my server, because now clients enter through the IP address in the browser, so it does not allow me to transmit to a Chromecast without https.  

If I do it through the jellyfin application, it will let me stream to a Chromecast.

**Comment by JustAMan** [comment]
Why cannot they use Jellyfin app and enter the address _there_?

**Comment by alexsoussa** [comment]
Because we want to offer a custom solution with our server only.

The people who use our server are our clients, so we want the application to be easy to use, for that we need to have the server configured by default.

**Comment by dkanada** [comment]
In that case I would be happy to let you know my rates for contract work! Let me know if you're interested and I can provide you with a nice solution for what I assume is some kind of educational video service? I have seen a few comments from businesses and schools in a similar situation.

**Comment by Artiume** [comment]
If you're looking to use this as a service and to have a business level commitment, it should be upon you to take the time and resources to make this happen. We've assisted in what way we can, but this is definitely something outside the scope of any bugs or issues that the community has and shouldn't be a problem for us to solve. 

Taking our time to solve your business problems does no one justice and hurts the community. By digging into the code yourself, you'll probably find potential bugs and issues that would be within your powers to fix or at least tell us about, but as it stands, that's not what's happening here.

**Comment by alexsoussa** [comment]
@Artiume I am very sorry if I could cause discomfort. I understand what you say and you're right, it's not your job and you don't have to.

Greetings and apologies again.

**Comment by dkanada** [comment]
@alexsoussa my offer still stands if you want a paid solution. We are all about open source and the software will always stay that way, but contributors have the freedom to work on whatever they want because this isn't our day job.

**Comment by alexsoussa** [comment]
@dkanada Yes! How can we get in contact to consider your offer?

**Comment by ferferga** [comment]
@alexsoussa Jellyfin is open source, so you're free to do whatever you want with the software (you would need to release the source code of your modifications if someone asks you, though), even charge for it. That's not wrong at all. The problem arises when you ask for our time in do that kind of stuff for your own business that doesn't benefit at all the community. Specially because doing what you want doesn't require a much of effort, just some hours of research and deep dive into the code.

As an example, I started making some modifications to my own server when I started using Jellyfin, some of them to suit my personal tastes, some others to change strings, logos, etc... Because it was a fun joke I had among my friends. However, I started doing all that tinkering myself, which helped me learn a lot of JS. That's the spirit of open source, you can do whatever you want with it and it helps you learn a lot because **you can** see what's going on behind the scenes.

Many of those modifications I did for joking with my friends and personal tastes ended up being incoporated to the main Jellyfin version that everybody uses right now. With that said, I encourage you that, with whatever business you have, make PRs that fixes stuff your users reports and report bugs that **actually** affects all of us.

That's also how the big boys like Google, Facebook, etc, play. They took a lot of the source code of Linux kernel, for example. However, they send bugfixes and improvements they faced while tinkering with the code and that's what is making Linux a better kernel each day.

I hope you understand the whole point better. I also encourage you to contribute, just like the big boys do (who don't want to be like them, eh?) :P

**Comment by MrTimscampi** [comment]
I'm wondering what kind of business that has the amount of money needed to properly license content for a legitimate streaming service would resort to using an open source solution and wouldn't have the team in house to build it :thinking:

**Comment by alexsoussa** [comment]
@ferferga For sure you are right! I'm sorry if I offended you with something I said.

I really appreciate your help!

@MrTimscampi that's none of your business ;)

**Comment by sparky8251** [comment]
This issue is outside the scope of the Jellyfin projecy. Closing

**Comment by ferferga** [comment]
@alexsoussa I think nobody here got offended at all, I re-state that we don't mind what you do with the code, if we would mind we would simply be closed-source :P.

**Comment by bubii** [comment]
> In that case I would be happy to let you know my rates for contract work! Let me know if you're interested and I can provide you with a nice solution for what I assume is some kind of educational video service? I have seen a few comments from businesses and schools in a similar situation.

Am interested. need a custom android app. what are your rates?
