### ISSUE TITLE
Protip: if you lock issues we can't reply to your comments

### ISSUE THREAD

**Issue by willymilkytron** [jellyfin/jellyfin-android#376]
Should we just shut up? Is this how you build your "welcoming community"? Silencing others because they don't agree with you? This is abuse of power.

> This is a formal warning. This behavior is unacceptable.

What does this mean??? @thornbill

**Comment by thornbill** [comment]
Locking the issue was a measure taken so that everyone could cool down before responding as the conversation was clearly not heading in a positive direction.

As far as the formal warning is concerned, please read this page in its entirety before continuing to interact here: https://jellyfin.org/docs/general/community-standards.html#dispute-resolution-and-moderation

**Comment by joshuaboniface** [comment]
Well at least your usename isn't `jellyfin-sucks-monkey-balls` any more. With that as your opener, I'm not sure exactly what you would expect from us.

Good riddance.
