### ISSUE TITLE
Permanently blocked at loading screen

### ISSUE THREAD

**Issue by willymilkytron** [jellyfin/jellyfin-android#44]
After signing in and out from a server the app is permanently blocked in a loading screen with no way to login, logout or change server. Only way to unblock is to clear app data from android app manager.

![Screenshot_1598255472](https://user-images.githubusercontent.com/62460473/91018112-73be0980-e5ef-11ea-851c-464cd7dbb5fa.png)

**Comment by Maxr1998** [comment]
Is this on the new client? I can't reproduce it on my setup.

**Comment by willymilkytron** [comment]
Yes, this is the new client

**Comment by willymilkytron** [comment]
https://imgur.com/a/Bf3aZBs

**Comment by Maxr1998** [comment]
I tried to reproduce this with the exact same steps, but couldn't. Maybe it's specific to your setup. Could you capture and upload a log for me, so that I can see whether it's related to the app or the web client?

**Comment by nielsvanvelzen** [comment]
I too, was unable to reproduce this issue. Can you give us more details like your server version?

**Comment by willymilkytron** [comment]
Server version is 10.6.0

**Comment by willymilkytron** [comment]
I just reproduced it on a clean install (throwaway docker container from image jellyfin/jellyfin:10.6.0)

**Comment by CarlosOlivo** [comment]
I don't know if it's the same error, but I found one that has a similar behavior

1. Start jellyfin server
2. Start jellyfin app & login
3. Kill jellyfin app
4. Kill jellyfin server
5. Start jellyfin app

**Expected behavior**: Initial screen to select server, since the last server is not available as in version v2.0.0-rc.3

![image](https://user-images.githubusercontent.com/25919231/92612692-bafafa00-f27f-11ea-84b2-1821e89828e7.png)

**Error**: Black screen with WebView error in jellyfin debug aka master branch
`09-09 09:10:50.422 E/MainActivity$initialize(16951): Received WebView error at http://192.168.100.2:8096/: net::ERR_CONNECTION_TIMED_OUT`

![image](https://user-images.githubusercontent.com/25919231/92612727-c2220800-f27f-11ea-80d2-31a6a5a1dd4b.png)

**Comment by nielsvanvelzen** [comment]
I tried starting the app with my server off and it does indeed cause issues. On my emulator it will show the issue from @willymilkytron. I think it doesn't do that for you @CarlosOlivo because for you the webview didn't load anything from cache.

@Maxr1998 I think we should (somehow) detect if the webview can't connect to the server and show an error (possibly within the connect screen). What do you think?

**Comment by Maxr1998** [comment]
> @Maxr1998 I think we should (somehow) detect if the webview can't connect to the server and show an error (possibly within the connect screen). What do you think?

We did have that already, but I had to remove it after it showed the login screen too often..

**Comment by willymilkytron** [comment]
Just to clarify: the original issue reported (by me) **has nothing to do** with the server being off

**Comment by nielsvanvelzen** [comment]
This should be solved by #231, a workaround for now is to change your device name to not include any special characters.
