### ISSUE TITLE
Add Changelogs To F-Droid

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin-android#516]
When updates are pushed to F-Droid, it doesn't show the changelogs.
Suggesting adding changelogs to F-Droid.

**Comment by nielsvanvelzen** [comment]
It's not possible to add changelogs to F-Droid with our current continuous integration process.

**Comment by seniorm0ment** [comment]
>our current integration process

are there any changes planned for the future?

**Comment by nielsvanvelzen** [comment]
No

**Comment by strugee** [comment]
@nielsvanvelzen what exactly is the problem with the current CI setup?

**Comment by strugee** [comment]
I think there's some terminology confusion here - I am _not_ suggesting creating >1 release in [GitHub releases](https://github.com/jellyfin/jellyfin-android/releases). This is the proposed workflow:

1. A maintainer tags a release and pushes to GitHub.
2. A maintainer creates a release in GitHub Releases tied to the tag in step 1.
3. CI notices this and creates Fastlane metadata based on the release created in step 2.
4. CI commits, tags and pushes a `-fdroid` tag.
5. Profit.

This means that there would be >1 tag, yes, but not >1 release. It also would not add any additional manual release steps for maintainers. [AFAICT](https://github.com/spotify/dh-virtualenv/releases) if a tag does not have a GitHub release associated with it, it does not show up on /releases, so this shouldn't be confusing to people.

(I hope I'm not bothering you with these questions - I had assumed that if we could find a different way that was acceptable from a maintenance perspective, this was something you'd be interested in doing, but maybe not?)

**Comment by nielsvanvelzen** [comment]
We don't want to add additional tags either. Support for changelogs should come from F-Droid (reading them from master / github changelogs / file published to repo.jellyfin.org) because we don't want to create additional releases / tags and don't want to change our release procedure right now.

Another solution to this problem is by hosting our own F-Droid repository because we can generate the metadata ourselves. I made a PoC a few months back for that but never finished it.
