### ISSUE TITLE
Navigationbar does not use style with API v28 and lower

### ISSUE THREAD

**Issue by wnhrt** [jellyfin/jellyfin-android#581]
### Describe the bug

Jellyfin shows a white navigation bar on my smartphone with Android 9 (API v28), despite dark mode enabled on OS and Jellyfin.

![Screenshot Light Navigationbar](https://user-images.githubusercontent.com/70302993/144925635-c27abf08-df03-45f4-9781-a512bb7a5feb.jpg)

Apparently, it has been possible to use a transparent color at least since Android 5 (API v21).
https://stackoverflow.com/questions/29069070/completely-transparent-status-bar-and-navigation-bar-on-lollipop
I havn't found any documentation.

I compiled it for my phone, with `<item name="android:navigationBarColor">@android:color/transparent</item>`, which worked fine but isn't really transparent.

![Screenshot Dark Navigationbar](https://user-images.githubusercontent.com/70302993/144928069-c2262fda-5844-469d-b38b-a42c20c122b3.jpg)

At least it should use `@color/jellyfin_primary_dark`, which gave the same result for me.

### Application version

2.4.1

### Device information

Samsung Galaxy S8

### Android version

Android 9

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
I think transparent doesn't work because the Webview still only fills the screen up to the navigation bar, but doesn't go below it. The white navigation bar seems to be a "Samsung problem", since on other Android devices the default is generally black. Either way, setting a color in the style like in your suggested PR should work, I'd personally just pick a different color. I'll comment on that over there though.

**Comment by nevenz** [comment]
This might have been fixed in v1.8.7.
