### ISSUE TITLE
Cannot play Live TV using External Players

### ISSUE THREAD

**Issue by jerry-yuan** [jellyfin/jellyfin-android#643]
### Describe the bug

1. Configure Jellyfin with a turner like HDHomeRun
2. Login Jellyfin Server via android client
3. Set the android client to use External Players like VLC
4. Try to streaming Live TV.
5. Got cannot play url.

### Application version

2.4.4 (Latest on Google Play)

### Where did you install the app from?

Google Play

### Device information

OnePlus 8T

### Android version

Android 11/Hydrogen OS 11.0.14.14.KB05

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by jerry-yuan** [comment]
The default web player(HTML Player) and integrated player(ExoPlayer) works well.

**Comment by hhhien2903** [comment]
Same problem.

**Comment by wpkato** [comment]
Same problem, I would use the ExoPlayer but won't play many other files I have in my instance.  An external player is much more robust

**Comment by dontobi** [comment]
I have a similar problem.

I use an external player (MX Player Pro). The reason is x265 encoded files that I want to play from my NAS. The integrated player (exoplayer) and also the web player cannot play these files smoothly.

But when I use the external player, the livetv stream does not work. The stream is provided via a M3U playlist from my TVHeadend server.

It can't be MX Player Pro because it plays the streams when I open them manually.

Apart from that, I have the problem that I have no sound when I play a LiveTV stream via the integrated player (exoplayer).

**Comment by tiagoqpinto** [comment]
Same problem here

**Comment by lovelyelfpop** [comment]
Same problem when play m3u8
