### ISSUE TITLE
Sometimes episode names do not show up completely

### ISSUE THREAD

**Issue by shalva97** [jellyfin/jellyfin-android#652]
### Describe the bug

I have a file named 
`/run/media/shalva/myHDD/downloads/[Anistar.org] The Gap of Time [TV-1] - 03 [1080p].mkv`

but on the app it shows up without the episode number

![Screenshot_20220426-232507_Jellyfin](https://user-images.githubusercontent.com/22417494/165377336-5d551a70-3003-4ae2-8c27-e489a9f5e39e.png)

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Xiaomi 10T

### Android version

LineageOS 18.1

### Jellyfin server version

10.7.7.0

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by fdornak** [comment]
Did you try to Edit metadata for this episode? (Three dots next to play button - Edit metadata). Does **title** contain episode number there?

If not it is not related to android client itself but jellyfin server. You can always edit metadata manually if jellyfin is not able to identify your TV show.

I would also assume that you did put this episode into movies library instead of TV shows.

**Comment by shalva97** [comment]
yea, at that time I was new to Jellyfin stuff. will close this
