### ISSUE TITLE
Subtitles cause media to be transcoded while device supports subtitles

### ISSUE THREAD

**Issue by YodaQ** [jellyfin/jellyfin-android#696]
### Describe the bug

On my phone (Samsung Node 8) as well as another phone (Samsung A52) when using the ExoPlayer and watching media stored in an mkv container with SSA/ASS subtitles the cause the entire video to transcode even though if you disable subtitles start the video then re-enable the subtitles the subtitles will play without requiring transcoding. This doesnt happen on the web player but the web player has the subtitles being out of sync issue.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Samsung Note 8

### Android version

Android 9

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
That's actually (mostly) intended, because ExoPlayer doesn't fully support SSA/ASS styling. Thus, we disabled support for them when using ExoPlayer. See google/ExoPlayer#8435 for more details.

It works in your case because we don't refresh the device profile when switching subs within the player. For the decision to direct play/transcode, only the initial configuration when starting playback counts at the moment.
