### ISSUE TITLE
ASS Subtitles not working

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-android#79]
**Describe the bug**

Playing video with embedded ASS subtitles doesn't display any subtitle.

**To Reproduce**

1. Download mkv anime from this season
2. Let jellyfin server index said anime
3. Play said anime on smartphone

**Expected behavior**

Subtitle visible when playing video

**Logs**

No error is displayed whatsoever

**Screenshots**

Sample video media info

![image](https://user-images.githubusercontent.com/62460473/91667368-624f9280-eb04-11ea-9f28-78663e83fc3d.png)

**System (please complete the following information):**
 - App version: v2.0.0-rc2
 - Android version: 5
 - Device manufacturer and model: Samsung Galaxy S5 Neo
 - Jellyfin server version: 10.6.0
 - The type of video player implementation used: default player, i think it's the "web" player

**Additional context**

Only workaround is manually set subtitles to "Off" and the select the subs track again. This sometimes triggers #46

**Comment by Maxr1998** [comment]
Like for the subtitle desync, I fear this is a web issue again. If I understand it correctly, the subtitles do occasionally show (or if using the workaround), but most times don't?

**Comment by willymilkytron** [comment]
> Like for the subtitle desync, I fear this is a web issue again.

It seems you're right, i just switched to ExoPlayer and i have not been able to reproduce this issue, so it's likely webplayer-only problem.

> If I understand it correctly, the subtitles do occasionally show (or if using the workaround), but most times don't?

Exactly.

**Comment by redactedscribe** [comment]
I couldn't get ASS subtitles to show no matter which subtitle option I selected for a movie: toggling to `Off`, `Sub - Eng`, or `Undefined` (external). This was with the Native player (I presume this is what people mean by ExoPlayer).

However, after numerous attempts, starts and stops etc, the subtitles started working immediately after switching to the Web player and playing it (albeit soon became unusable due to the [de-sync](#46) bug). After that, I switched back to the Native player and subtitles were _still_ working (and no de-syncing despite a lot of seeking). That was only temporary: If I stopped the Native player playback (returned to menu / home screen) and navigated to hit play on the video again, the subtitles were now gone and no matter the options I selected, they wouldn't come back. (`Play method: Transcode` and `Transcoding: true`).

I'm not sure how Jellyfin works, but my guess is the _Web player_ is extracting the subtitles fine, and they remain on-disk after switching to the Native player. But once I stop the Native player, Jellyfin discards the transcoded files, and on pressing play again, the Native player won't extract the subs. Technically, the players aren't the ones doing the extracting I guess, but you get my point, I hope.

Curiously, this seems limited to only when _transcoding_: playing a different video (a series) via the _Native player_ (`Play method: DirectStream` and `Transcoding: false`), the ASS subs are extracted fine and there is no issue (I can turn the subs on and off at will).

---

Media Info (for the transcoded video/_movie_):

Container: `mkv`
| Video | Audio | Subtitle | Subtitle |
| -- | --| -- | -- |
| Title 1080p HEVC | Title Eng AAC 5.1 Default | Title Sub - Eng | Title Undefined |
| Codec HEVC | Language eng | Language eng | Codec ASS |
| Profile Main 10 | Codec AAC | Codec ASS | Default No |
| Level 120 | Profile LC | Default No | Forced No |
| Resolution 1916x1080 | Layout 5.1 | Forced No | External Yes |
| Aspect ratio 16:9 | Channels 6 ch | External No |
| Interlaced No | Bitrate 320 kbps |
| Framerate 23.976025 | Sample rate 48000 Hz |
| Bitrate 1749 kbps | Default Yes |
| Pixel format yuv420p10le |
| Ref frames 1 |

Media Info (for the DirectStream video/_series_):

Container: `mkv`
| Video | Audio | Subtitle | Subtitle |
| -- | --| -- | -- |
| Title 1080p H264 | Title Jpn FLAC stereo Default | Title Sub - Eng - Default | Title Undefined |
| Codec H264 | Language Jpn | Language Eng | Codec ASS |
| AVC No | Codec FLAC | Codec ASS | Default No |
| Profile High | Layout Stereo | Default Yes | Forced No |
| Level 41 | Channels 2 ch | Forced No | External Yes |
| Resolution 1920x1080 | Sample rate 48000 Hz | External No | 
| Aspect ratio 16:9 | Bit depth 16 bit |
| Interlaced No | Default Yes |
| Framerate 23.976025 |
| Bitrate 6532 kbps |
| Bit depth 8 bit |
| Pixel format yuv420p |
| Ref frames 1 |
| NAL 0 |

---

After some more testing, it seems that this bug is related to the subtitle selection option on the summary screen, the one shown before pressing play on a video (the page with the date, runtime, ratings, etc).

Once I changed the embedded subtitle's Default status to `true` (using MKVToolNix), the video now plays with subtitles. Granted, re-copying the container may have fixed some errors in the MVK itself, but I don't think that was the case: If you choose to start playing _this particular movie_ with subtitles turned Off (via that prior summary screen), it's impossible to switch the subtitles on when the video is playing. Same goes for if you start this video _with_ a subtitle selected: the subtitles will now work, but it's impossible to turn them off. This, again, is all in the Native player.

Current conclusion seems to be subtitle selection is somehow bugged. If a subtitle track isn't turned on before playing a video (because it wasn't manually selected, or wasn't automatically set due to not being the default), subtitles cannot be displayed for the video.

Something else curious: the subtitles shown for the transcoded movie, seem styled (and not according to the app's subtitle settings as far as I could tell). The DirectStream series however should have some fancy styled subs, but they are all displayed with a black background.

It's hard to pin down exactly what's happening, or what's the cause, but hopefully that wasn't too confusing and may help provide some clues.

Thanks.

**Comment by nielsvanvelzen** [comment]
Note that ExoPlayer doesn't really support ASS or SSA subtitles, I'd recommend enabling transcoding for those.

**Comment by redactedscribe** [comment]
That may be why it's a bit buggy then. Are there any plans for it to support SubStation Alpha subs?

I assume you mean to turn off `Allow subtitle extraction on the fly`? ("Disable this to have embedded subtitles burned in with video transcoding when they are not natively supported by the client device."). That's a solution I guess, but now _all_ content will have burned-in subs I presume.

I could convert the ASS subs to SRT, but that could turn out a mess depending how styled the sub is. I don't know if Jellyfin will already automatically choose an SRT over an ASS/SSA sub when using the Native player, but that may be a good idea (_if_ SRT is supported).

**Comment by Artiume** [comment]
https://github.com/google/ExoPlayer/issues/8435
