### ISSUE TITLE
Integrated & External video player type forces Direct Play streaming mode

### ISSUE THREAD

**Issue by Behem07h** [jellyfin/jellyfin-android#844]
### Describe the bug

1. Go to Client Settings, change Video Player Type to "Integrated Player" or "External Player"
2. Go to Playback settings, change all video quality and music quality settings to a very low bitrate to ensure the file being streamed would need transcoding to meet the limit
3. Stream a video, and inspect the video's Media Info
4. Observe that all videos get streamed using the Direct Play streaming method at their original bitrate, despite being way over the bitrate requested by the client in Playback settings

Tested on latest version of Jellyfin Player both from FDroid and Playstore

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Umidigi A11

### Android version

Android 11

### Jellyfin server version

latest

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by foux** [comment]
This one is really problematic, because it renders external player / exoplayer completely unusable when on low bandwidth conditions

**Comment by MrShoenel** [comment]
This is still a problem and has not been resolved.

**Comment by Clubfan22** [comment]
I think I've run into a related manifestation of this bug:
When using the external player (in my case VLC) and trying to stream a video with a higher bitrate than the internet streaming limit from a non-local network, playback immediately fails with a "Media cannot be played by this device" toast.
I've tracked the error down to [JellyfinMediaSource.kt:29](https://github.com/jellyfin/jellyfin-android/blob/efbd93911ec83a1de87a184c59975cf2e346a97b/app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt#L29) where apparently no playback method is supported. I suppose that's because the server forces transcoding due to the bitrate limit, but the ExternalPlayerProfile only supports direct play.
