### ISSUE TITLE
No volume control

### ISSUE THREAD

**Issue by Salamandar** [jellyfin/jellyfin-android#978]
### Describe the bug

* Play a video
* try to change the volume either with the buttons or the touchscreen
* no volume change, max volume even if the system volume is 0
![Screenshot_20230213-234440_Jellyfin](https://user-images.githubusercontent.com/6552989/218591434-cfd0cceb-d719-4989-b49f-c187eb6f1d1c.png)

![Screenshot_20230213-234444_Jellyfin](https://user-images.githubusercontent.com/6552989/218591441-cc4b144f-9621-4fd3-b8e0-57fba4e00824.png)

Ou can see the "remote sonud system" icon, seems usual because it shows when playing a youtube video as well

### Application version

2.4.4

### Where did you install the app from?

F-Droid

### Device information

Xiaomi Redmi Note 9

### Android version

Android 12 (/e/os 1.8)

### Jellyfin server version

10.8.5

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by TheGreenSlimeOG** [comment]
Facing the same issue here, on Android 13. However, I'm able to control the volume when my Bluetooth headphones/speakers are connected. 
I thought it was only me until I stumbled upon this.

**Comment by Mahir-M01** [comment]
Facing the exact same issue here. However, I did notice that I was able to control the volume when my Bluetooth headphones / speakers were connected.
I'm on Android 13.

**Comment by Quinten0508** [comment]
+1 on this issue. Happens on the official Jellyfin app as well as on Findroid.

Running Android 13 - Jellyfin ver. 2.5.0-beta.2

**Comment by Susxy** [comment]
Same here. 

Android 13 LineageOS 20
Jellyfin 2.5.0-beta.4

**Comment by Quinten0508** [comment]
The problem lies in using surround sound audio. Anything dolby/7.1/5.1 will not allow you to control volume, but if you convert the audio track to stereo it'll work fine again. 

Don't know how the internals of this app work, but could it be that these extra channels are not being controlled when we change the volume and thus remain at full volume?

**Comment by Maxr1998** [comment]
I just tested this myself with the Dolby Atmos trailer (TrueHD 7.1 with Atmos) and couldn't reproduce it on both the integrated player and the web player. The "remote playback" icon is kinda odd and might be what's causing the issue, but I'm not sure. Did you use the app to play audio before attempting video playback?

**Comment by Maxr1998** [comment]
Could you check if this also happens with this file?
https://www2.iis.fraunhofer.de/AAC/ChID-BLITS-EBU.mp4

**Comment by Susxy** [comment]
Yes, i couldn't change volume with this video too.

**Comment by Maxr1998** [comment]
Could you send me a sample file then? I haven't found a way to otherwise reproduce this yet.

**Comment by Quinten0508** [comment]
I personally cannot reproduce the issue when using the default web player on the Jellyfin app. Using ExoPlayer *does* still break volume changing. Playing back a `.wav` audio file with 7.1 surround using Jellyfin does not present the same problem. This might suggest the problem lies within ExoPlayer.

So far (using ExoPlayer!) I've been able to reproduce the issue on all videos with audio tracks that have more than 2 channels (stereo). This includes:
* Dolby TrueHD 7.1 Atmos 		(8 channels)
* DTS-HD MA 7.1						(8 channels)
* DD 5.1										(6 channels)

[Here](https://www.demolandia.net/downloads.html?id=919165883) is a sample video file with Dolby 7.1 which does `not` allow changing volume when played back on an Android device. Feel free to try it out.


Sidenote: the setting `Maximum allowed audio channels` within the Jellyfin app does not seem to have any effect. Shouldn't this setting theoretically "fix" this bad behavior?

**Comment by notdeadyett** [comment]
I have the same issue. 5.1 and 7.1 audio files cause full volume playback even if the device is at 0. 

No issues with stereo files.

**Comment by Salamandar** [comment]
That might be coherent as why I sometimes have this issue, and sometimes I don’t. The media in the initial screenshot was a 5.1 file.

**Comment by gudvinr** [comment]
Most likely it's OS issue and not Jellyfin issue as you can't control volume in both internal and external (mpv) player.

Here's lineage os issue I filed:  
https://gitlab.com/LineageOS/issues/android/-/issues/6116

It's not uncommon since I found other old issues (linked there)

**Comment by Wraaath** [comment]
Just to wanted to add a fix that worked for me (LineageOS-20 kebab):

Using Findroid, I changes
Settings -> Player -> mpv-player -> Audio output -> opensles

That solved the issue of the Jellyfin playing at one constant audio level, and playing both thru phone speakers and earbuds.

Hope this helps :)

**Comment by gregismotion** [comment]
Same issue, Findroid. mpv player crashes.
